from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
                url('about', views.aboutus ),
                url(r'^signup$',views.signup),
                #url(r'^logout$',views.logout),
                url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
                url(r'^sold/([0-9]{1,5})$',views.sold),
                url(r'^contactfeedback$',views.contact_feedback),
                url(r'^sales$',views.sale_requests),
                url(r'^deleteproduct/([0-9]{1,5})$',views.deleteproduct),
                url(r'^deletecategory/([0-9]{1,5})$',views.deletecategory),
                url(r'^editCategory$',views.editCategory),
                url(r'^editCategory/([0-9]{1,5})$',views.editCategory),
                url(r'^addCategory',views.addCategory),
                url(r'^adminCategory',views.adminCategory),
                url(r'^editProduct$',views.editProduct),
                url(r'^editProduct/([0-9]{1,5})$',views.editProduct),
                url(r'^addProduct',views.addProduct),
                url(r'^adminProducts',views.adminProducts),
                #url(r'^login-in',views.log_in),
                url(r'^login/$', views.log_in, name='login'),
                url(r'^loginpage',views.loginPage),
                url(r'^search',views.search),
                url(r'^saveclient',views.saveclient),
                url(r'^editsession',views.editsession),
                url(r'^delete',views.deletesession),
                url(r'^order',views.order),
                url(r'^remove/([0-9]{1,5})/([0-9]{1,5})$',views.sessionremove),
                url(r'^cartvalue',views.cartvalue),
                url(r'^empty',views.empty),
                url(r'^checkout',views.checkout),
                url(r'^add-to-cart',views.add_to_cart),
                url(r'^product/([0-9]{1,5})$',views.product_details),
                url(r'^category/([0-9]{1,5})$',views.category),
                url('how-to-buy', views.howToBuy),
                url('contact', views.contact ),
                url('^$', views.index),
               ]
